# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.8.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.8.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lucy/Desktop/doing/compile_principle/LuciCompiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lucy/Desktop/doing/compile_principle/LuciCompiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.8.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.8.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lucy/Desktop/doing/compile_principle/LuciCompiler/CMakeFiles /Users/lucy/Desktop/doing/compile_principle/LuciCompiler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lucy/Desktop/doing/compile_principle/LuciCompiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lucc

# Build rule for target.
lucc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lucc
.PHONY : lucc

# fast build rule for target.
lucc/fast:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/build
.PHONY : lucc/fast

ast.o: ast.c.o

.PHONY : ast.o

# target to build an object file
ast.c.o:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/ast.c.o
.PHONY : ast.c.o

ast.i: ast.c.i

.PHONY : ast.i

# target to preprocess a source file
ast.c.i:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/ast.c.i
.PHONY : ast.c.i

ast.s: ast.c.s

.PHONY : ast.s

# target to generate assembly for a file
ast.c.s:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/ast.c.s
.PHONY : ast.c.s

env.o: env.c.o

.PHONY : env.o

# target to build an object file
env.c.o:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/env.c.o
.PHONY : env.c.o

env.i: env.c.i

.PHONY : env.i

# target to preprocess a source file
env.c.i:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/env.c.i
.PHONY : env.c.i

env.s: env.c.s

.PHONY : env.s

# target to generate assembly for a file
env.c.s:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/env.c.s
.PHONY : env.c.s

errmsg.o: errmsg.c.o

.PHONY : errmsg.o

# target to build an object file
errmsg.c.o:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/errmsg.c.o
.PHONY : errmsg.c.o

errmsg.i: errmsg.c.i

.PHONY : errmsg.i

# target to preprocess a source file
errmsg.c.i:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/errmsg.c.i
.PHONY : errmsg.c.i

errmsg.s: errmsg.c.s

.PHONY : errmsg.s

# target to generate assembly for a file
errmsg.c.s:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/errmsg.c.s
.PHONY : errmsg.c.s

escape.o: escape.c.o

.PHONY : escape.o

# target to build an object file
escape.c.o:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/escape.c.o
.PHONY : escape.c.o

escape.i: escape.c.i

.PHONY : escape.i

# target to preprocess a source file
escape.c.i:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/escape.c.i
.PHONY : escape.c.i

escape.s: escape.c.s

.PHONY : escape.s

# target to generate assembly for a file
escape.c.s:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/escape.c.s
.PHONY : escape.c.s

frame-mips.o: frame-mips.c.o

.PHONY : frame-mips.o

# target to build an object file
frame-mips.c.o:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/frame-mips.c.o
.PHONY : frame-mips.c.o

frame-mips.i: frame-mips.c.i

.PHONY : frame-mips.i

# target to preprocess a source file
frame-mips.c.i:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/frame-mips.c.i
.PHONY : frame-mips.c.i

frame-mips.s: frame-mips.c.s

.PHONY : frame-mips.s

# target to generate assembly for a file
frame-mips.c.s:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/frame-mips.c.s
.PHONY : frame-mips.c.s

ir.o: ir.c.o

.PHONY : ir.o

# target to build an object file
ir.c.o:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/ir.c.o
.PHONY : ir.c.o

ir.i: ir.c.i

.PHONY : ir.i

# target to preprocess a source file
ir.c.i:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/ir.c.i
.PHONY : ir.c.i

ir.s: ir.c.s

.PHONY : ir.s

# target to generate assembly for a file
ir.c.s:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/ir.c.s
.PHONY : ir.c.s

lexer.o: lexer.c.o

.PHONY : lexer.o

# target to build an object file
lexer.c.o:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/lexer.c.o
.PHONY : lexer.c.o

lexer.i: lexer.c.i

.PHONY : lexer.i

# target to preprocess a source file
lexer.c.i:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/lexer.c.i
.PHONY : lexer.c.i

lexer.s: lexer.c.s

.PHONY : lexer.s

# target to generate assembly for a file
lexer.c.s:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/lexer.c.s
.PHONY : lexer.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/main.c.s
.PHONY : main.c.s

parser.o: parser.c.o

.PHONY : parser.o

# target to build an object file
parser.c.o:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/parser.c.o
.PHONY : parser.c.o

parser.i: parser.c.i

.PHONY : parser.i

# target to preprocess a source file
parser.c.i:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/parser.c.i
.PHONY : parser.c.i

parser.s: parser.c.s

.PHONY : parser.s

# target to generate assembly for a file
parser.c.s:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/parser.c.s
.PHONY : parser.c.s

ppast.o: ppast.c.o

.PHONY : ppast.o

# target to build an object file
ppast.c.o:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/ppast.c.o
.PHONY : ppast.c.o

ppast.i: ppast.c.i

.PHONY : ppast.i

# target to preprocess a source file
ppast.c.i:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/ppast.c.i
.PHONY : ppast.c.i

ppast.s: ppast.c.s

.PHONY : ppast.s

# target to generate assembly for a file
ppast.c.s:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/ppast.c.s
.PHONY : ppast.c.s

ppir.o: ppir.c.o

.PHONY : ppir.o

# target to build an object file
ppir.c.o:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/ppir.c.o
.PHONY : ppir.c.o

ppir.i: ppir.c.i

.PHONY : ppir.i

# target to preprocess a source file
ppir.c.i:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/ppir.c.i
.PHONY : ppir.c.i

ppir.s: ppir.c.s

.PHONY : ppir.s

# target to generate assembly for a file
ppir.c.s:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/ppir.c.s
.PHONY : ppir.c.s

semantic.o: semantic.c.o

.PHONY : semantic.o

# target to build an object file
semantic.c.o:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/semantic.c.o
.PHONY : semantic.c.o

semantic.i: semantic.c.i

.PHONY : semantic.i

# target to preprocess a source file
semantic.c.i:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/semantic.c.i
.PHONY : semantic.c.i

semantic.s: semantic.c.s

.PHONY : semantic.s

# target to generate assembly for a file
semantic.c.s:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/semantic.c.s
.PHONY : semantic.c.s

symbol.o: symbol.c.o

.PHONY : symbol.o

# target to build an object file
symbol.c.o:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/symbol.c.o
.PHONY : symbol.c.o

symbol.i: symbol.c.i

.PHONY : symbol.i

# target to preprocess a source file
symbol.c.i:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/symbol.c.i
.PHONY : symbol.c.i

symbol.s: symbol.c.s

.PHONY : symbol.s

# target to generate assembly for a file
symbol.c.s:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/symbol.c.s
.PHONY : symbol.c.s

table.o: table.c.o

.PHONY : table.o

# target to build an object file
table.c.o:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/table.c.o
.PHONY : table.c.o

table.i: table.c.i

.PHONY : table.i

# target to preprocess a source file
table.c.i:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/table.c.i
.PHONY : table.c.i

table.s: table.c.s

.PHONY : table.s

# target to generate assembly for a file
table.c.s:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/table.c.s
.PHONY : table.c.s

temp.o: temp.c.o

.PHONY : temp.o

# target to build an object file
temp.c.o:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/temp.c.o
.PHONY : temp.c.o

temp.i: temp.c.i

.PHONY : temp.i

# target to preprocess a source file
temp.c.i:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/temp.c.i
.PHONY : temp.c.i

temp.s: temp.c.s

.PHONY : temp.s

# target to generate assembly for a file
temp.c.s:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/temp.c.s
.PHONY : temp.c.s

translate.o: translate.c.o

.PHONY : translate.o

# target to build an object file
translate.c.o:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/translate.c.o
.PHONY : translate.c.o

translate.i: translate.c.i

.PHONY : translate.i

# target to preprocess a source file
translate.c.i:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/translate.c.i
.PHONY : translate.c.i

translate.s: translate.c.s

.PHONY : translate.s

# target to generate assembly for a file
translate.c.s:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/translate.c.s
.PHONY : translate.c.s

types.o: types.c.o

.PHONY : types.o

# target to build an object file
types.c.o:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/types.c.o
.PHONY : types.c.o

types.i: types.c.i

.PHONY : types.i

# target to preprocess a source file
types.c.i:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/types.c.i
.PHONY : types.c.i

types.s: types.c.s

.PHONY : types.s

# target to generate assembly for a file
types.c.s:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/types.c.s
.PHONY : types.c.s

utils.o: utils.c.o

.PHONY : utils.o

# target to build an object file
utils.c.o:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/utils.c.o
.PHONY : utils.c.o

utils.i: utils.c.i

.PHONY : utils.i

# target to preprocess a source file
utils.c.i:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/utils.c.i
.PHONY : utils.c.i

utils.s: utils.c.s

.PHONY : utils.s

# target to generate assembly for a file
utils.c.s:
	$(MAKE) -f CMakeFiles/lucc.dir/build.make CMakeFiles/lucc.dir/utils.c.s
.PHONY : utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... lucc"
	@echo "... ast.o"
	@echo "... ast.i"
	@echo "... ast.s"
	@echo "... env.o"
	@echo "... env.i"
	@echo "... env.s"
	@echo "... errmsg.o"
	@echo "... errmsg.i"
	@echo "... errmsg.s"
	@echo "... escape.o"
	@echo "... escape.i"
	@echo "... escape.s"
	@echo "... frame-mips.o"
	@echo "... frame-mips.i"
	@echo "... frame-mips.s"
	@echo "... ir.o"
	@echo "... ir.i"
	@echo "... ir.s"
	@echo "... lexer.o"
	@echo "... lexer.i"
	@echo "... lexer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... ppast.o"
	@echo "... ppast.i"
	@echo "... ppast.s"
	@echo "... ppir.o"
	@echo "... ppir.i"
	@echo "... ppir.s"
	@echo "... semantic.o"
	@echo "... semantic.i"
	@echo "... semantic.s"
	@echo "... symbol.o"
	@echo "... symbol.i"
	@echo "... symbol.s"
	@echo "... table.o"
	@echo "... table.i"
	@echo "... table.s"
	@echo "... temp.o"
	@echo "... temp.i"
	@echo "... temp.s"
	@echo "... translate.o"
	@echo "... translate.i"
	@echo "... translate.s"
	@echo "... types.o"
	@echo "... types.i"
	@echo "... types.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

